title: My Awesome Site
email: your-email@example.com
description: This is my personal blog.
baseurl: ""
url: "" # the base hostname & protocol for your site,
# e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from being processed
exclude:
  - Gemfile
  - Gemfile.lock